// <auto-generated />
using System;
using CncApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CncApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224122929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CncApp.Domain.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int>("BarAmountPlanned")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("BarCycleTime")
                        .HasColumnType("time");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartAmountPlanned")
                        .HasColumnType("int");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("MachineId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockLotId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("HeatNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PartAmountRequested")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("PartsPerBar")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<TimeSpan>("ApproxPartCycleTime")
                        .HasColumnType("time");

                    b.Property<int>("CheckPerPart")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeSpan?>("Downtime")
                        .HasColumnType("time");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("PartsMade")
                        .HasColumnType("int");

                    b.Property<int>("Scrap")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.HasIndex("JobId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.StockLot", b =>
                {
                    b.Property<int>("StockLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockLotId"));

                    b.Property<int>("AmountOfBars")
                        .HasColumnType("int");

                    b.Property<decimal>("BarLength")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CheckedInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Condition")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Diameter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("StockLotId");

                    b.HasIndex("MaterialId");

                    b.ToTable("StockLots");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.StockLotAdjustment", b =>
                {
                    b.Property<int>("StockLotAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockLotAdjustmentId"));

                    b.Property<int>("DeltaBars")
                        .HasColumnType("int");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.Property<int>("StockLotId")
                        .HasColumnType("int");

                    b.HasKey("StockLotAdjustmentId");

                    b.HasIndex("StockLotId");

                    b.ToTable("StockLotAdjustments");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<byte>("RoleType")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("UserId", "RoleType")
                        .IsUnique()
                        .HasFilter("[AuditTrail_DisabledAtDateTime] IS NULL");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Job", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.Machine", "Machine")
                        .WithMany("Jobs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CncApp.Domain.Entities.Order", "Order")
                        .WithMany("Jobs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CncApp.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Order");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Order", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.Part", "Part")
                        .WithMany("Orders")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Shift", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.Job", "Job")
                        .WithMany("Shifts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CncApp.Domain.Entities.User", "Operator")
                        .WithMany("Shifts")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.Material", "Material")
                        .WithMany("StockLots")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.StockLotAdjustment", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.StockLot", "StockLot")
                        .WithMany("StockLotAdjustments")
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CncApp.Domain.Common.AuditTrail", "AuditTrail", b1 =>
                        {
                            b1.Property<int>("StockLotAdjustmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("CreatedByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DisabledAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("DisabledByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("UpdatedByUserId")
                                .HasColumnType("int");

                            b1.HasKey("StockLotAdjustmentId");

                            b1.ToTable("StockLotAdjustments");

                            b1.WithOwner()
                                .HasForeignKey("StockLotAdjustmentId");
                        });

                    b.Navigation("AuditTrail")
                        .IsRequired();

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CncApp.Domain.Common.AuditTrail", "AuditTrail", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("CreatedByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DisabledAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("DisabledByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("UpdatedByUserId")
                                .HasColumnType("int");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("AuditTrail")
                        .IsRequired();
                });

            modelBuilder.Entity("CncApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("CncApp.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CncApp.Domain.Common.AuditTrail", "AuditTrail", b1 =>
                        {
                            b1.Property<int>("UserRoleId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("CreatedByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("DisabledAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("DisabledByUserId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("UpdatedAtDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<int?>("UpdatedByUserId")
                                .HasColumnType("int");

                            b1.HasKey("UserRoleId");

                            b1.ToTable("UserRoles");

                            b1.WithOwner()
                                .HasForeignKey("UserRoleId");
                        });

                    b.Navigation("AuditTrail")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Job", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Machine", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Material", b =>
                {
                    b.Navigation("StockLots");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Order", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.Part", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.StockLot", b =>
                {
                    b.Navigation("StockLotAdjustments");
                });

            modelBuilder.Entity("CncApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
